services:
  - type: web
    name: scalping-bot
    env: python
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install -e .
    startCommand: python main.py
buildCommand: |
  python -m pip install --upgrade pip setuptools wheel
  pip install --no-deps -e .
